name: OWASP ZAP Scan

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Debug: list files and confirm app.py exists
      - name: Debug: list files
        run: ls -la

      # Run Flask app in background
      - name: Run Flask app
        run: |
          nohup python app.py &
          sleep 10

      # Health check: ensure Flask is running
      - name: Check Flask app is reachable
        run: |
          curl -I http://localhost:5000 || (echo "Flask not reachable" && exit 1)

      # Run OWASP ZAP baseline scan
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://host.docker.internal:5000'
          cmd_options: '-a'

      # Upload ZAP report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
